import type {Metadata} from "next";
import {GeistSans} from "geist/font/sans"; // Import font
import "../../styles/globals.css"; // Import global styles
import React from 'react';
import Sidebar from '../../components/Sidebar';
import Header from '../../components/Header';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        // Add font to className, also add antialiased and dark mode
        <html lang="en" className={`${GeistSans.className} antialiased dark:bg-gray-950`}>
        <body>
        <div className="min-h-screen flex bg-gray-100 dark:bg-gray-950">
            <Sidebar/> {/* Navigation bar component */}
            <div className="flex-1 p-6">
                <Header/> {/* Header component with settings menu */}
                <main>
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
